services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        aptmirror: ${APT_MIRROR:-ftp.riken.jp/Linux/ubuntu}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/workspace:cached
      - ${VENV:-venv}:/workspace/.venv
      - ${NODE_MODULES:-node_modules}:/workspace/node_modules
      - ${HOME_CACHE:-~/.cache}:/home/vscode/.cache
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    privileged: true
    environment:
      - DISPLAY=:0
volumes:
  node_modules:
  venv:
