#!/bin/sh

cd `dirname $0`/..

# remove
rm -rf build

# package python
poetry install --no-root &&
poetry run virtualenv --always-copy build/.venv &&
poetry export --without dev > requirements.lock &&
build/.venv/bin/python -m pip install -r requirements.lock &&
build/.venv/bin/python -m pip uninstall -y pip &&

# package electron
yarn package
